# fly.toml app configuration file generated for vepeen on 2023-05-25T15:56:02+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vepeen"
primary_region = "sin"
kill_signal = "SIGINT"

[env]
  PORT = "41641"

[[mounts]]
  source = "root"
  destination = "/"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641
  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
